
/*XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX*/


CREATE OR REPLACE FUNCTION public.salvar()
 RETURNS boolean
 LANGUAGE plpgsql
AS $function$
BEGIN
COPY (SELECT * FROM public.sesion ) TO 'D:/archivo.csv' WITH CSV;
RETURN true;
END;
$function$
;
